In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('credit_train.csv')
del df['Loan ID']
del df['Customer ID']

In [3]:
# df.info()
df=df[0:100000]


In [4]:
df.columns[df.isnull().any()]


Index(['Credit Score', 'Annual Income', 'Years in current job',
       'Months since last delinquent', 'Maximum Open Credit', 'Bankruptcies',
       'Tax Liens'],
      dtype='object')

In [6]:
l=[1,4,5,6]

In [7]:
for col in ['Loan Status','Term','Years in current job', 'Home Ownership','Purpose',]:
    df[col] = df[col].fillna('None')

In [8]:
for cil in ['Current Loan Amount','Credit Score','Annual Income','Monthly Debt', 'Years of Credit History',
       'Months since last delinquent', 'Number of Open Accounts',
       'Number of Credit Problems', 'Current Credit Balance',
       'Maximum Open Credit', 'Bankruptcies', 'Tax Liens']:
    df[cil]=df[cil].fillna(int(0))

In [54]:
df

Loan Status  Current Loan Amount        Term  Credit Score  \
0       Fully Paid             445412.0  Short Term         709.0   
1       Fully Paid             262328.0  Short Term           0.0   
2       Fully Paid           99999999.0  Short Term         741.0   
3       Fully Paid             347666.0   Long Term         721.0   
4       Fully Paid             176220.0  Short Term           0.0   
5      Charged Off             206602.0  Short Term        7290.0   
6       Fully Paid             217646.0  Short Term         730.0   
7      Charged Off             648714.0   Long Term           0.0   
8       Fully Paid             548746.0  Short Term         678.0   
9       Fully Paid             215952.0  Short Term         739.0   
10      Fully Paid           99999999.0  Short Term         728.0   
11      Fully Paid             541970.0  Short Term           0.0   
12      Fully Paid           99999999.0  Short Term         740.0   
13      Fully Paid           99999999.0  Short Term         743.0   
14      Fully Paid             234124.0  Short Term         727.0   
15      Fully Paid             449020.0   Long Term           0.0   
16     Charged Off             653004.0   Long Term           0.0   
17      Fully Paid             666204.0   Long Term         723.0   
18      Fully Paid              66396.0  Short Term           0.0   
19      Fully Paid             390390.0  Short Term         747.0   
20     Charged Off             317108.0   Long Term         687.0   
21      Fully Paid             128238.0  Short Term         750.0   
22     Charged Off             153252.0  Short Term         714.0   
23      Fully Paid              91894.0  Short Term         724.0   
24      Fully Paid             244926.0   Long Term         704.0   
25      Fully Paid             465410.0   Long Term         688.0   
26      Fully Paid           99999999.0  Short Term         724.0   
27      Fully Paid             443960.0  Short Term         749.0   
28      Fully Paid           99999999.0  Short Term         746.0   
29      Fully Paid             107404.0  Short Term           0.0   
...            ...                  ...         ...           ...   
99970   Fully Paid           99999999.0  Short Term         674.0   
99971   Fully Paid           99999999.0   Long Term         616.0   
99972   Fully Paid             328350.0   Long Term         704.0   
99973   Fully Paid             522610.0   Long Term         725.0   
99974   Fully Paid             330528.0  Short Term         731.0   
99975  Charged Off             274076.0  Short Term         736.0   
99976   Fully Paid             333630.0  Short Term           0.0   
99977   Fully Paid             483428.0  Short Term           0.0   
99978   Fully Paid             431860.0   Long Term           0.0   
99979   Fully Paid             766392.0  Short Term         717.0   
99980   Fully Paid             336776.0  Short Term         745.0   
99981  Charged Off             666666.0  Short Term         725.0   
99982   Fully Paid             484968.0   Long Term           0.0   
99983   Fully Paid             758450.0  Short Term         726.0   
99984   Fully Paid             347468.0  Short Term         691.0   
99985   Fully Paid             179454.0  Short Term         708.0   
99986   Fully Paid             781022.0  Short Term         741.0   
99987   Fully Paid             277882.0  Short Term         711.0   
99988  Charged Off             309474.0  Short Term           0.0   
99989  Charged Off             429132.0  Short Term           0.0   
99990   Fully Paid           99999999.0  Short Term         742.0   
99991   Fully Paid             244266.0  Short Term         714.0   
99992   Fully Paid              48796.0  Short Term           0.0   
99993   Fully Paid              44484.0  Short Term         717.0   
99994   Fully Paid             210584.0  Short Term         719.0   
99995   Fully Paid             147070.0  Short Term         725.0   
99996

In [9]:
y=df.iloc[:,0].values
y

array(['Fully Paid', 'Fully Paid', 'Fully Paid', ..., 'Fully Paid',
       'Fully Paid', 'Fully Paid'], dtype=object)

In [10]:
X=df.iloc[:,1:].values
X

array([[445412.0, 'Short Term', 709.0, ..., 416746.0, 1.0, 0.0],
       [262328.0, 'Short Term', 0.0, ..., 850784.0, 0.0, 0.0],
       [99999999.0, 'Short Term', 741.0, ..., 750090.0, 0.0, 0.0],
       ...,
       [103136.0, 'Short Term', 742.0, ..., 537548.0, 1.0, 0.0],
       [530332.0, 'Short Term', 746.0, ..., 738254.0, 0.0, 0.0],
       [99999999.0, 'Short Term', 743.0, ..., 91014.0, 1.0, 0.0]],
      dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_x=LabelEncoder()
for m in l:   
    X[:,m]=label_x.fit_transform(X[:,m])
    onehotencoder=OneHotEncoder(categorical_features=[m])

In [10]:
X[0]

array([445412.0, 1, 709.0, 1167493.0, 8, 1, 5, 5214.74, 17.2, 0.0, 6.0,
       1.0, 228190.0, 416746.0, 1.0, 0.0], dtype=object)

In [12]:
X=onehotencoder.fit_transform(X).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [13]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_x=LabelEncoder()
y=label_x.fit_transform(y)
onehotencoder=OneHotEncoder(categorical_features=[])

In [14]:
#to show full array
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

# Classifiers

# 1 Logistic Regression

In [97]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_test=sc_X.fit_transform(X_test)
X_train=sc_X.fit_transform(X_train)

In [98]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=42)

In [99]:
classifier.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=42, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [100]:
y_pred=classifier.predict(X_test)

In [101]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [102]:
cm

array([[ 1424,  5388],
       [   30, 23158]], dtype=int64)

In [20]:
from sklearn.metrics import classification_report

In [104]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_pred,target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.98      0.21      0.34      6812
     class 1       0.81      1.00      0.90     23188

   micro avg       0.82      0.82      0.82     30000
   macro avg       0.90      0.60      0.62     30000
weighted avg       0.85      0.82      0.77     30000




## Naive Bias

In [105]:
from sklearn.naive_bayes import GaussianNB


In [106]:
classifierNB=GaussianNB()
classifierNB.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [107]:
y_predNB=classifierNB.predict(X_test)

In [108]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predNB)

In [109]:
cm

array([[ 6289,   523],
       [17227,  5961]], dtype=int64)

In [110]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_predNB,target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.27      0.92      0.41      6812
     class 1       0.92      0.26      0.40     23188

   micro avg       0.41      0.41      0.41     30000
   macro avg       0.59      0.59      0.41     30000
weighted avg       0.77      0.41      0.40     30000



## DECISION TREE

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
classifierDT=DecisionTreeClassifier(criterion='entropy',random_state=42)
classifierDT.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=42,
            splitter='best')

In [16]:
y_predDT=classifierDT.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predDT)
cm

array([[ 2932,  3880],
       [ 3479, 19709]], dtype=int64)

In [20]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_predDT,target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.46      0.43      0.44      6812
     class 1       0.84      0.85      0.84     23188

   micro avg       0.75      0.75      0.75     30000
   macro avg       0.65      0.64      0.64     30000
weighted avg       0.75      0.75      0.75     30000



## Random Forest

In [14]:
from sklearn.ensemble import RandomForestClassifier
classifierRF=RandomForestClassifier(n_estimators=10, random_state=0,criterion='entropy')
classifierRF.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [15]:
y_predRF=classifierRF.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predRF)
cm

array([[ 2260,  4552],
       [ 1349, 21839]], dtype=int64)

In [19]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_predRF,target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.63      0.33      0.43      6812
     class 1       0.83      0.94      0.88     23188

   micro avg       0.80      0.80      0.80     30000
   macro avg       0.73      0.64      0.66     30000
weighted avg       0.78      0.80      0.78     30000



## SVM

In [13]:
from sklearn.svm import SVC


In [ ]:
classifierSVM=SVC(kernel='linear',random_state=42)
classifierSVM.fit(X_train,y_train)

In [ ]:
y_predSVM=classifierSVM.predict(X_test)


In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predSVM)
cm

In [ ]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_predSVM,target_names=target_names))

## KNN

In [26]:
from sklearn.neighbors import KNeighborsClassifier
classifierKNN=KNeighborsClassifier(n_neighbors=8)
classifierKNN.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=8, p=2,
           weights='uniform')

In [27]:
y_predKNN=classifierKNN.predict(X_test)

In [28]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predKNN)
cm

array([[ 1173,  5639],
       [ 2523, 20665]], dtype=int64)

In [29]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_predKNN,target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.32      0.17      0.22      6812
     class 1       0.79      0.89      0.84     23188

   micro avg       0.73      0.73      0.73     30000
   macro avg       0.55      0.53      0.53     30000
weighted avg       0.68      0.73      0.70     30000

